artifacts_root: artifacts


data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://drive.google.com/file/d/1cm860h09dE3i7fN23Q7J7uVpaQE8bghm/view?usp=sharing
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion
    
prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.h5
    
training:
    root_dir: artifacts/training
    trained_model_path: artifacts/training/model.h5
    prod_model_path: model/model.h5
    
evaluation:
    path_of_model: artifacts/training/model.h5
    training_data: artifacts/data_ingestion/Corn_Leaf_Health_Dataset
    mlflow_uri: https://dagshub.com/tymoteuszdobrucki/Corn-Leaf-Health.mlflow